[tool.poetry]
name = "dash-extensions-docs"
version = "0.0.1"
description = ""
authors = ["emher <emil.h.eriksen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
dash = "2.3.1"
dash-extensions = "0.1.0rc5"
dash-mantine-components = "^0.7.0"
dash-iconify = "^0.1.0"
dash-labs = "^1.0.3"
mistune = "^2.0.2"
mistletoe = "^0.8.2"
pytest = "^7.1.1"
coverage = "^6.3.2"
dash-down = "^0.0.8"

[tool.poetry.dev-dependencies]
quart = "^0.17.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
